name: Dependabot Auto-merge

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * MON-FRI"

jobs:
  dependabot-automerge:
    name: Dependabot Auto-merge
    uses: navikt/mob-gha-workflows/.github/workflows/dependabot-automerge-v2.yaml@main
    secrets:
      APP_ID: ${{ vars.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    with:
      ignored-dependencies: "react,react-dom"  